### ISSUE TITLE
address data not correct

### ISSUE THREAD

**Issue by GlWy** [e-Contract/commons-eid#11]
I guess that retrieving the address works like this:
Address address = TlvParser.parse(idData, Address.class);

However, what is returned is are numbers. For instance: 

- streetAndNumber contains the cardNumber
- municipality contains a date
 
Is the the wrong approach to retrieve the address? Am I missing something? I have added a screenshot which shows the code and the retrieved data.

<img width="1290" alt="eid get address" src="https://user-images.githubusercontent.com/11777113/33116401-e1371974-cf64-11e7-9a80-f0009df9dace.png">

**Comment by fcorneli** [comment]
You are parsing the wrong file for address data.
Try the following:
```
final byte[] addressData = card.readFile(FileType.Address);
final Address address = TlvParser.parse(addressData, Address.class);
```

**Comment by GlWy** [comment]
Ok, thanks.
I was obviously sleeping when I tried this our.

Thanks for the quick response

**Comment by fcorneli** [comment]
Coffee :)
