### ISSUE TITLE
Default BeIDCardManager connects to cards using Protocol.ANY

### ISSUE THREAD

**Issue by Nepherte** [e-Contract/commons-eid#13]
The api documentation of BeIDCardManager states:

> "Instantiate a BeIDCardManager [...] that only connects to Cards with Protocol T=0"

However, the following pseudo code proves otherwise:

```
BeIDCardManager cardManager = new BeIDCardManager();
PROTOCOL protocol = cardManager.CardAndTerminalManager.protocol;
assertThat(protocol, is(PROTOCOL.T0); // results in an assertion error
```

The issue is that the field `terminalManagerIsPrivate` is set to true only _after_ the protocol is set on the cardAndTerminalManager.

**Comment by Nepherte** [comment]
Setting the protocol to T0 on cardAndTerminalManager relies on the fact that terminalManagerIsPrivate is true. The constructors that don't take a CardAndTerminalManager set this flag to true only after it is used to determine whether protocol T0 should be set. The actual protocol would then be the default one set in CardAndTerminalManager, which is protocol ANY.

It ultimately boils down to the incorrect initialization sequence / usage of the field terminalManagerIsPrivate. Making it final would eventually lead to  a fix for this problem. 

```
private boolean terminalManagerIsPrivate; // 1. initially false

public BeIDCardManager() {
  this(new VoidLogger());
}

public BeIDCardManager(final Logger logger) {
  this(logger, new CardAndTerminalManager());
  this.terminalManagerIsPrivate = true; // 3. now true, but at at this point the protocol is already set
}

public BeIDCardManager(final Logger logger, final CardAndTerminalManager cardAndTerminalManager) {
  [...]
  if (this.terminalManagerIsPrivate) { // 2. at this point still false
    this.cardAndTerminalManager.setProtocol(PROTOCOL.T0);
  }
 [...]
}
```

**Comment by fcorneli** [comment]
Will be fixed in next version.
