### ISSUE TITLE
Cannot sign with  Elliptic Curve Digital Signature Algorithm

### ISSUE THREAD

**Issue by gitounet** [e-Contract/commons-eid#18]
Hi,

- commons-eid 1.1.1
- bouncycastle jdk18on 1.77
- Java 1.8.0_412

When attempting to sign CMS content with EDCA, using the commons-eid BeIDECPrivateKey  along with the bouncycastle library, we get the following error:

java.lang.UnsupportedOperationException
	at be.fedict.commons.eid.jca.BeIDECPrivateKey.getS(BeIDECPrivateKey.java:64)
	at sun.security.ec.ECDSASignature.signDigestNative(ECDSASignature.java:346)
	at sun.security.ec.ECDSASignature.engineSign(ECDSASignature.java:385)
	at java.security.Signature$Delegate.engineSign(Signature.java:1380)
	at java.security.Signature.sign(Signature.java:696)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder$1.getSignature(Unknown Source)
	at org.bouncycastle.cms.SignerInfoGenerator.generate(Unknown Source)
	at org.bouncycastle.cms.CMSSignedDataGenerator.generate(Unknown Source)
	at org.bouncycastle.cms.CMSSignedDataGenerator.generate(Unknown Source)

Here is the a code excerpt:

```CMSTypedData content = new CMSProcessableByteArray(contentToSign);
CMSSignedDataGenerator generator = new CMSSignedDataGenerator();
JcaSignerInfoGeneratorBuilder signerInfoGeneratorBuilder = new JcaSignerInfoGeneratorBuilder(new JcaDigestCalculatorProviderBuilder().build());
ContentSigner contentSigner = new JcaContentSignerBuilder("SHA256WITHECDSA").build(signatureCredential.getPrivateKey());
CMSAttributeTableGenerator cmsAttributeTableGenerator = new DefaultSignedAttributeTableGenerator();
signerInfoGeneratorBuilder.setSignedAttributeGenerator(cmsAttributeTableGenerator);
generator.addSignerInfoGenerator(signerInfoGeneratorBuilder.build(contentSigner, signatureCredential.getCertificate()));
generator.generate(content);
```

Is there a way to sign with EDCA and a beid private key?

**Comment by fcorneli** [comment]
Did you try out the latest version of Commons eID?

**Comment by fcorneli** [comment]
```
sun.security.ec.ECDSASignature.signDigestNative(ECDSASignature.java:346)
```
Of course this cannot work. The Sun ECDSASignature does not know how to handle our eID EC keys.
Try the following:
```
Security.insertProviderAt(new BeIDProvider(), 1);
```
Magic isn't it? :)

**Comment by fcorneli** [comment]
See also:
https://github.com/e-Contract/commons-eid/blob/master/commons-eid-tests/src/test/java/test/integ/be/fedict/commons/eid/client/CMSTest.java

**Comment by gitounet** [comment]
Thanks a lot for pointing me to the unit test. It succeeds if I run it with an eid using SHA256withRSA, but it fails with an eid using SHA256withECDSA (same UnsupportedOperationException error).

**Comment by fcorneli** [comment]
Is it the same eID that you use for both tests? If so, this cannot work. An eID supports either RSA or ECDSA.

**Comment by fcorneli** [comment]
You should get the following output for an EC eID card:
```
Running test.integ.be.fedict.commons.eid.client.CMSTest
DEBUG [BeIDProvider] newInstance: KeyStore
DEBUG [BeIDKeyStore] engineLoad
DEBUG [BeIDKeyStore] engineGetKey: Authentication
DEBUG [AbstractBeIDPrivateKey] constructor: AuthentificationCertificate
DEBUG [BeIDKeyStore] engineGetCertificate: Authentication
DEBUG [BeIDProvider] newInstance: Signature
DEBUG [BeIDSignature] constructor: SHA256withECDSA
DEBUG [BeIDProvider] supportsParameter: be.fedict.commons.eid.jca.BeIDECPrivateKey@3fabf088 for algo SHA256withECDSA = true
DEBUG [BeIDProvider] newInstance: Signature
DEBUG [BeIDSignature] constructor: SHA256withECDSA
DEBUG [BeIDSignature] engineInitSign
DEBUG [BeIDSignature] engineSign
DEBUG [AbstractBeIDPrivateKey] auto recovery: false
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.284 s -- in test.integ.be.fedict.commons.eid.client.CMSTest
```

**Comment by gitounet** [comment]
I have found my issue: the SunEC provider is included in my jdk and takes precedence over BeIDProvider. To have BeIDProvider take priority I have added the following lines after inserting the  BeIDProvider:

```
Security.insertProviderAt(new BeIDProvider(), 1);
...
Security.removeProvider("SunEC");
Security.addProvider(new sun.security.ec.SunEC());
```
