### ISSUE TITLE
Java 

### ISSUE THREAD

**Issue by Atlanta001** [e-Contract/commons-eid#4]
Can I read this only with java in the console platform.
For the moment I can only compile the eid-tests folder and I am reading only my name and not my picture and address.
<img width="911" alt="knipsel" src="https://cloud.githubusercontent.com/assets/10586890/18351100/152c6dba-75d9-11e6-9a97-75033d9b4f56.PNG">

Where can I find the commons-eid source  code for java windowBuilder engine?

<img width="888" alt="knipsel1" src="https://cloud.githubusercontent.com/assets/10586890/18351208/8cc1fb42-75d9-11e6-8ba9-a2cd101c4213.PNG">

Or is there another way to compile the project in a extern exe platform

**Comment by fcorneli** [comment]
mvn clean install
