### ISSUE TITLE
BeIDCards.getAllBeIDCards() contains cards in unrecoverable state after using the FedICT EID Viewer

### ISSUE THREAD

**Issue by dwagelaar** [e-Contract/commons-eid#6]
Calling readFile() on such a BeIDCard results in the following exception:

javax.smartcardio.CardException: beginExclusive() failed
	at sun.security.smartcardio.CardImpl.beginExclusive(CardImpl.java:216)
	at be.fedict.commons.eid.client.BeIDCard.beginExclusive(BeIDCard.java:1019)
	at be.fedict.commons.eid.client.BeIDCard.readFile(BeIDCard.java:1138)
	at be.healthconnect.emr.client.eid.EIDHelper.getUntrustedIdentity(EIDHelper.java:67)
	... 7 more
Caused by: sun.security.smartcardio.PCSCException: SCARD_W_RESET_CARD
	at sun.security.smartcardio.PCSC.SCardBeginTransaction(Native Method)
	at sun.security.smartcardio.CardImpl.beginExclusive(CardImpl.java:213)
	... 10 more

The only way to recover from this, is to re-insert the eID card in the reader. The FedICT EID Viewer has no problem doing subsequent card reads, and does not require card re-inserts.

**Comment by dwagelaar** [comment]
OS: Windows 10 Enterprise 64-bits

**Comment by dwagelaar** [comment]
Suggested fix in pull request https://github.com/e-Contract/commons-eid/pull/7

**Comment by dwagelaar** [comment]
Some elaboration on the initial comment:

1. Start your application, and initialize a singleton BeIDCards instance for the remainder of the application runtime.
2. The BeIDCards instance receives card events for the currently inserted cards, and stores those cards in an internal collection.
3. Start another application that accesses the eID, such as the FedICT EID Viewer. The EID Viewer will read the card on startup.
4. The BeIDCard instance stored inside BeIDCards has now been "hi-jacked" by the other application, and no further transactions can be made on it by your own application.

The fix iterates over all known cards, and tests for this condition. Unusable BeIDCard instances are discarded and replaced by new ones.

**Comment by fcorneli** [comment]
Merged all. Thanks for the contribution.
