### ISSUE TITLE
List of operating systems where commons-eid is guaranteed to work

### ISSUE THREAD

**Issue by wouterbeckers** [e-Contract/commons-eid#8]
Hello,

Is there a list (or could you provide a list) of operating systems on which commons-eid is guaranteed to work? We know it works on windows, but are wondering about other systems.

Thanks in advance,

Wouter Beckers

**Comment by fcorneli** [comment]
Commons eID has been tested on Windows, Mac OS X and Linux.

**Comment by fcorneli** [comment]
https://github.com/e-Contract/commons-eid/commit/4dd3c7eebbf9144db8dd8761fbb8d2799d309897
